### ISSUE TITLE
Failed to activate the switcheroo package

### ISSUE THREAD

**Issue by arthur-e** [adrianolaru/switcheroo#2]
[Enter steps to reproduce below:]

1. Start atom from command line (`atom .`)
2. Hit FN + F8, my key combo for Switcheroo.

**Atom Version**: 0.207.0
**System**: Ubuntu 14.04.2
**Thrown From**: [switcheroo](https://github.com/adrianolaru/switcheroo) package, v0.5.0

### Stack Trace

Failed to activate the switcheroo package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/home/arthur/.atom/packages/switcheroo/lib/switcheroo.coffee:8:32)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:238:19)
    at /usr/share/atom/resources/app.asar/src/package.js:770:25
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:219:20)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)
```

### Commands

```
     -0:00.5.0 switcheroo:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".SyncID",
      ".SyncIgnore",
      ".SyncArchive"
    ],
    "projectHome": "/usr/local/dev/",
    "audioBeep": false,
    "disabledPackages": [
      "open-on-github",
      "package-generator",
      "autocomplete",
      "spell-check",
      "welcome",
      "autosave",
      "background-tips",
      "bookmarks",
      "deprecation-cop",
      "image-view",
      "link",
      "release-notes",
      "snippets",
      "styleguide"
    ]
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v0.3.3
language-latex, v0.4.1
markdown-preview-pandoc, v0.0.12
switcheroo, v0.5.0

# Dev
No dev packages
```

**Comment by rugk** [comment]
Just after installing and if I press F8 with v1.1.0 this issue still happens.

**Comment by adiospace** [comment]
It works fine on my comp. It happens even if you restart atom?

**Comment by rugk** [comment]
Oh no after restarting it works correctly. :smiley:  But this error was displayed directly after the update.

**Comment by adiospace** [comment]
Glad it works. I'll have a look later, see what's going on... Thank you.
